[project]
name = "b3m"
version = "0.1.1"
description = "modular successor to b3p"
authors = [
    { name = "wr1", email = "8971152+wr1@users.noreply.github.com" },
]
readme = "README.md"
dependencies = [
    "treeparse",
    "statesman",
    "pydantic",
    "pyyaml",
    "tomli>=2.3.0",
    "tomli-w>=1.2.0",
    "b3-geo @ git+https://github.com/wr1/b3_geo.git@dev1",
    "b3_msh @ git+https://github.com/wr1/b3_msh.git@mul3d1",
    "b3_drp @ git+https://github.com/wr1/b3_drp.git@dev1",
    "b3-2d @ git+https://github.com/wr1/b3_2d.git@dev3",
    "b3_mat @ git+https://github.com/wr1/b3_mat.git@dev1",
    "cgfoil @ git+https://github.com/wr1/cgfoil.git@dev1",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "pytest-cov",
    "loguru",
    "tomli",
    "tomli-w",
]
bem = [
    "ccblade",
    "b3_bem @ git+https://github.com/wr1/b3_bem.git@dev1",
]

[project.scripts]
b3m = "b3m.cli:main"
b3m-build = "b3m.integration:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
