workdir: example_workdir
geometry:
  planform:
    z:
      - [0.0, 0.0]
      - [1.0, 1.0]
    chord:
      - [0.0, 1.0]
      - [1.0, 0.5]
    thickness:
      - [0.0, 0.1]
      - [1.0, 0.05]
    twist:
      - [0.0, 0.0]
      - [1.0, 10.0]
    dx:
      - [0.0, 0.0]
      - [1.0, 0.0]
    dy:
      - [0.0, 0.0]
      - [1.0, 0.0]
    npchord: 200
    npspan: 100
airfoils:
  - path: naca0018.dat
    name: naca0018
    thickness: 0.18
mesh:
  z:
    - type: linspace
      values: [0.0, 1.0]
      num: 10
  chordwise:
    default:
      n_elem: 100
    panels: []
structure:
  webs: []
